---
- name: Setup vLLM and Open WebUI Docker Environment
  hosts: localhost
  become: true
  gather_facts: true
  tasks:
    - name: Install Docker Python module (if not present)
      pip:
        name: docker
        state: present

    - name: Ensure Docker service is running
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Add current user to the docker group
      user:
        name: "leckhoff"
        groups: docker
        append: yes
      register: user_group_change

    - name: Reset ssh connection to allow user group changes to take effect
      meta: reset_connection
      when: user_group_change.changed

    - name: Wait for Docker daemon to be ready
      wait_for:
        path: /var/run/docker.sock
        state: present
        timeout: 30

    - name: Set proper permissions on Docker socket
      file:
        path: /var/run/docker.sock
        mode: '0666'
      when: user_group_change.changed

    - name: Test Docker access without sudo
      command: docker info
      become: false
      register: docker_test
      retries: 3
      delay: 5
      until: docker_test.rc == 0
      environment:
        USER: "leckhoff"

    - name: Pull the vLLM Docker image from Docker Hub
      docker_image:
        name: "vllm/vllm-openai:latest"
        source: pull
        timeout: 600  # Increased timeout for large image
      become: false
      retries: 2
      delay: 10

    - name: Pull the Open WebUI Docker image from GitHub Container Registry
      docker_image:
        name: "ghcr.io/open-webui/open-webui:main"
        source: pull
        timeout: 600  # Increased timeout
      become: false
      retries: 2
      delay: 10

    - name: Verify images were pulled successfully
      command: docker images
      become: false
      register: docker_images_output

    - name: Display pulled images
      debug:
        msg: "{{ docker_images_output.stdout_lines }}"
