---
- name: Pull Application-Specific Docker Images
  hosts: all
  become: true # Required to interact with the system's Docker daemon

  tasks:
    - name: Pull the vLLM Docker image from Docker Hub
      community.docker.docker_image:
        name: "vllm/vllm-openai:latest"
        source: pull

    - name: Pull the Open WebUI Docker image from GitHub Container Registry
      community.docker.docker_image:
        name: "ghcr.io/open-webui/open-webui:main"
        source: pull
        
    - name: Add remote user to the docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}" # This automatically targets the user you SSH'd with
        groups: docker
        append: yes # This is crucial to add the group, not replace all other groups
