---
- name: Setup vLLM and Open WebUI Docker Environment
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Install Docker Python module (if not present)
      pip:
        name: docker
        state: present

    - name: Ensure Docker service is running
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Add remote user to the docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      register: user_group_change

    - name: Reset ssh connection to allow user group changes to take effect
      meta: reset_connection
      when: user_group_change.changed

    - name: Wait for Docker daemon to be ready
      wait_for:
        port: 2375
        host: localhost
        timeout: 30
      ignore_errors: true

    - name: Test Docker access without sudo
      command: docker info
      become: false
      register: docker_test
      retries: 3
      delay: 5
      until: docker_test.rc == 0

    - name: Pull the vLLM Docker image from Docker Hub
      docker_image:
        name: "vllm/vllm-openai:latest"
        source: pull
        timeout: 300
      become: false
      retries: 2
      delay: 10

    - name: Pull the Open WebUI Docker image from GitHub Container Registry
      docker_image:
        name: "ghcr.io/open-webui/open-webui:main"
        source: pull
        timeout: 300
      become: false
      retries: 2
      delay: 10

    - name: Verify images were pulled successfully
      command: docker images
      become: false
      register: docker_images_output

    - name: Display pulled images
      debug:
        msg: "{{ docker_images_output.stdout_lines }}"
